### ISSUE TITLE
Insert type doesn't put in typeclass

### ISSUE THREAD

**Issue by devshorts** [atom-haskell/ide-haskell#93]
Giving ide-haskell a whirl today and was trying to add a type to a simple function:

```
transform str = length str
```

Which in ghci gives me 

```
Prelude > :t transform
transform :: Foldable t => t a -> Int
```

But when I add do insert type in atom I get:

```
transform :: t a -> Int
transform str = length str
```

Which of course gives compilation errors since the typeclass is missing.  Am I doing something wrong?

**Comment by lierdakil** [comment]
I would guess this is upstream issue: https://github.com/kazu-yamamoto/ghc-mod/issues/69

**Comment by devshorts** [comment]
Interesting, this works in sublime-text on my local too. Does sublimehaskell use a different version of ghc-mod?

**Comment by lierdakil** [comment]
You can notice that referenced upstream issue have been reopened recently due to regression. Last time I checked, I believe sublime-haskell tried to install specific version of ghc-mod in a sandbox environment, but I'm not entirely sure it's the case now.

**Comment by DanielG** [comment]
@devshorts can you check which version you're using it would be helpful to know where to put the good revision for a git bisect.

**Comment by devshorts** [comment]
@DanielG I'm on ide-haskell 0.7.1 with ghc-mod version 5.3.0.0 compiled by GHC 7.10.2

**Comment by DanielG** [comment]
Hmmm but that shouldn't be the version that's working I'm pretty sure this is broken in 5.3. Well anyways I'm investigating that issue now either way.

**Comment by devshorts** [comment]
Ah, I am a moron and didn't read "good revision". My bad.

**Comment by lierdakil** [comment]
Okay, so this should be working with ghc-mod 5.6.0.0. Feel free to open new issues if it doesn't.
